### ISSUE TITLE
[Bug]:  Table's variant `relaxed` and `normal`

### ISSUE THREAD

**Issue by vanessatran-ddi** [GovAlta/ui-components#1466]
### Describe the bug

The variant `relaxed` and `normal` make no difference. 
![image](https://github.com/GovAlta/ui-components/assets/120135417/8acafbb6-eabc-434c-9e30-71752643ce71)
![image](https://github.com/GovAlta/ui-components/assets/120135417/2a34e017-c511-4d90-a2fe-eda704879ee2)

They are no different, regarding about the padding in the table cell. 
Definition of "variant" 
variant: A relaxed variant of the table with more vertical padding for the cells

### To Reproduce

https://deploy-preview-27--abgov-ui-component-docs.netlify.app/components/table
Sandbox, when changing the variant property, makes no difference.

**Comment by Spark450** [comment]
@vanessatran-ddi it looks like we can get both normal and relaxed table variants to display in storybook. Does that mean that this could be sandbox issue?

**Comment by bdfranck** [comment]
The CSS selectors for relaxed rows (and a sticky header) don't work because the `goa-table` element doesn't get a `relaxed` or `sticky` class.

https://github.com/GovAlta/ui-components/blob/b69048853d5bc2b6f1e8bc96eece8759e1a08636/libs/web-components/src/assets/css/components.css#L83-L90

It looks like the wrapper `div` in the element's shadow DOM that get these classes 👀.

![Image](https://github.com/GovAlta/ui-components/assets/1479091/4eaaef1e-3dfc-49e5-8540-18895ddf32ce)

I'm not sure how best to approach it. I'll need to spend more time researching how to style a slotted element in this situation. 🤔
