### ISSUE TITLE
[Bug]: Search Input in Filterable Dropdown is Being Autofilled

### ISSUE THREAD

**Issue by francisagyapong-goa** [GovAlta/ui-components#1510]
### Describe the bug

When Dropdown is autofilled, a value isn't actually set in the Dropdown, the change event isn't fired.

### Provide Code

Please use https://purchasing.dev.alberta.ca/supplier-registration to confirm this behaviour. Recording of a walkthrough has also been attached here.
[supplier-registration-autofill-behaviour-2023-12-11_08.56.44.webm](https://github.com/GovAlta/ui-components/assets/94571832/410933c0-67fc-402a-8c3d-1506f657bb09)

NOTE: I can't get autofill to work in StackBlitz but here's code similar to what we have in our application: https://stackblitz.com/edit/b1due8?file=src%2Fapp%2Fapp.component.html

### To Reproduce

Accept browser's autofill suggestion

### What browsers are you seeing the problem on?

Chrome, Edge

## Acceptance Criteria

1. Make sure change event is fired when Dropdown is auto-filled so that Dropdown actually has a value.

**Comment by chrisolsen** [comment]
I can't replicate this issue and neither can their code snippet. 

The autocomplete was disabled web-component v1.18 which is the same version set in the stackblitz code example, so I am wondering if the original bug is in an older version before the fix. @francisagyapong-goa Can you let us know what version of the web-component library you are using in the app?

**Comment by francisagyapong-goa** [comment]
@chrisolsen We're still able to reproduce it - we're using web-components version 1.18.1 (the linked stackblitz uses 1.18.0).

The issue is that a filterable dropdown's search input is autofilled causing the user to think a value has been selected when in fact there's no value bound to it.

**Comment by francisagyapong-goa** [comment]
@chrisolsen @vanessatran-ddi Was this only released for web-components, v1.17.x? We're currently on version 1.18.1.

**Comment by BumbleB2na** [comment]
For anyone referencing this issue from now on please see [this updated stackblitz demo](https://stackblitz.com/edit/b1due8-j6yh1h7c?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts). It demonstrates how to populate Province/State dropdown with subdivisions from all countries by default; whenever there is no Country option selected the Province/State dropdown should contain all possible options so that autofill can select one. Autofill in Chrome browser can populate fields in a form the moment it is applied, so it does not populate dynamic fields later on. Custom code can be used to accomplish that, but the dropdown component does not support that out of the box. This comment is in reference to #2303 where autofill on dropdown component has been revisited.
