### ISSUE TITLE
[Bug][Figma]: goa-TextArea component in Figma inconsistent with coded version

### ISSUE THREAD

**Issue by jim-muirhead** [GovAlta/ui-components#2117]
### Describe the bug

The goa-TextArea component in Figma does not match the coded goa-TextArea component in appearance or behaviour. These are the items in the Figma component that do not align with the coded version:

1. • Text overflow does not “scroll” upwards to leave the last entered text visible at the bottom of the text input area (just above the character-count bar). 

2. Input field auto-increases in height when text overflows the height set (4 lines, etc.) instead of maintaining the height set and scrolling the content upwards in the text input field.

3. The character-counter bar does not extend across the full-width of the text input field or extend down to the bottom of the text input field.

4. The character-counter bar does not have a pale-blue fill to clip/mask any overflow content.

5. When scrolling the contents in the input field, they are not clipped by the character-counter bar across the bottom of the text input field.

### To Reproduce

1. Drop the goa-TextArea component into any Figma page.
2. Set the height of the component to 4 lines.
3. Turn on the character-count feature.
4. Turn on Content and paste in enough text to exceed the 4 line height restriction set.

**Comment by twjeffery** [comment]
_Reposting from Slack:_

Hey @jim-muirhead , I published a few changed to the Figma component to fix this. 

I added the ability to show a scroll bar, and set the heights to fixed depending on the number of lines/rows you want to set for it so that you can more easily mock up what you are describing.

A couple things to note:
- The blue fill to clip the text does not exist in our developed component
- In Figma we are not able to set the text to align to the bottom (to leave the last entered text at the bottom) as this would mean if there is a small amount of text, it would start aligned at the bottom of the text area. This is something that you can set in context in the component when you need to mock that up, by adjusting the auto layout in that instance. You can do this without detaching the component as well.
