### ISSUE TITLE
[Bug][Figma]: goa-Input-Label component does not wrap properly when length of label exceeds width of field.

### ISSUE THREAD

**Issue by jim-muirhead** [GovAlta/ui-components#2151]
### Describe the bug

In Figma, the goa-Input-Label component should have auto-layout set to Wrap, so that if there is not enough room for the label, the label itself and/or the (optional)/(required) elements will wrap to a second line underneath the first line of the label.

Wrong Behaviour
![image](https://github.com/user-attachments/assets/a7a9e272-8d90-4b7c-bd33-c2a96d652a3e)

Correct Behaviour
![image](https://github.com/user-attachments/assets/c3f3629e-b1a7-4d9b-b713-5135eb73be38)
![image](https://github.com/user-attachments/assets/fafd23a3-4077-490b-a850-3da7280c5c10)

### To Reproduce

1. Place a component that uses the Goa-Input-Label sub-component into a Figma page and set the width of the main component to a fixed width.
2. Set the field/component to "(optional)".
3. Type in a long field label until it exceeds the width of the component.

**Comment by jim-muirhead** [comment]
Sorry about the extra images - can't seem to delete them.

**Comment by twjeffery** [comment]
copying from Slack support channel:

@jim-muirhead  Unfortunately this is a limitation of Figma. We are not yet able to wrap text WITH other items. In this case, two different text blocks, same as an icon or badge inline with text.

This forum thread explains the issue a bit:
https://forum.figma.com/t/how-to-wrap-texts-with-auto-layout/59844/3
For now we just need to adjust that manually in design. But this works in development, so that's good!

There are often cases where we don't want the text label to wrap with the input - e.g. a narrow checkbox list, a known width of 6 characters on an input, and other shorter inputs, we wouldn't want the text label to wrap with the input.

![image](https://github.com/user-attachments/assets/f36dea1c-7917-430f-879a-b20d4292e238)

Given Figma's limitation here, I think manually setting these to wrap or fill when needed is a decent work around until we can wrap text inline with other items like we can in code.
