### ISSUE TITLE
Enhance card component so that it can accept custom content

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#236]
Card component currently does not accept custom content in the "body" section.

**Comment by jonathanweyermann** [comment]
The body section (description) currently does not accept jsx (react), but the title does. We would like the description to accept jsx just like the title of the card component currently does

**Comment by jonathanweyermann** [comment]
Also, it looks like the card component is not currently visible in the react version of ui-components 
![image](https://user-images.githubusercontent.com/11400938/143484340-170d8aac-a653-4930-9037-a79eaa4f8486.png)

**Comment by Spark450** [comment]
Hey @jonathanweyermann would you be able to let me know what version you are using?

**Comment by chrisolsen** [comment]
@jonathanweyermann Looking at the code `content`, like the title and footer, does accept a `ReactNode`. Description is a deprecated property, but will be rendered if no `content` is specified.
![image](https://user-images.githubusercontent.com/41582/143494385-337a5f64-faad-421a-bc83-9f1ff1fe7663.png)

As for the card not appearing in storybook that is because the version that currently exists in `lib` is deprecated so removing it from the docs hopefully prevents it's usage.
