### ISSUE TITLE
Investigate `eslint` and `prettier` for automated code quality assurance

### ISSUE THREAD

**Issue by cjam** [GovAlta/ui-components#247]
## Overview
Investigate the use of `eslint` and `prettier` to automate the code quality and formatting to improve the consistency of the codebase and give contributors more automated feedback with respects to the coding standards.

## Background
This issue was surface from a discussion with @cjam and @chrisolsen as part of a larger discussion about service team needs and contribution to the design system.

## Acceptance criteria
 - [ ] Meet with Ashnav Kumar for demo and knowledge transfer
 - [ ] Investigate the potential of creating a eslint package for the DIO coding standards
 - [ ] Use the DIO eslint / prettier configs to ensure code quality and formatting of contributions to the ui-components repo

**Comment by Spark450** [comment]
Hi @cjam I had a chance to chat with @chrisolsen this morning and he told me that we already have linting and formatting in place. We still would like to meet to discuss getting the NX templates setup #246  👍 

In light of this recent info I will close #247 so that we can focus our efforts on the template work. Thanks, Colter!

**Comment by cjam** [comment]
Sound good @Spark450, Ashnav has experience in creating custom rules for eslint in the event that @chrisolsen would like to have more granular control of enforcing code quality of contributions.
