### ISSUE TITLE
Update Callout documentation in Figma to include "smallout"

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#435]
**As a:** Front-end designer
**I want:** Use the "smallout" variant of the callout
**so that:** In "data-dense" contexts I can include a variant of the callout that is more compact an incorporated better into the layout. 

Link to AE designs
[Smallout](https://www.figma.com/file/CbNt3NFotKnLy2cHIsQ92i/AE-Design-System?node-id=224%3A1303)

### Acceptance criteria
- [ ] Create a new name other than "smallout" that is more consistent with how we are speaking about "compact" and "relaxed" layout variants
- [ ] Add "smallout" variant to the existing callout component
- [ ] Recreate callout page of documentation in Figma
- [ ] Update callout documentation to include reference to "smallout" and provide guidance on it usage
  - [ ] Discuss this with Chris Martin (creator of the smallout variant)
- [ ] Manual design review

### Presentable outcomes
- [ ] I can show updated documentation and Figma component during the sprint review

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
GitHub issue: corresponding Dev issue #436 

### Resources:
**Mockups:** [Callout]
(https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=3800%3A118527)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by ambroseyau** [comment]
The padding spacing and line-height for the "small-outs" are inconsistent.
- Created another variation of the small-outs with new spacing
- Started working on the documentation 
Setting up with a meeting with Chris Martin to go through the the intention behind the design.

**Comment by ambroseyau** [comment]
Had a discussion with Chris Martin to identify possible use cases for small-outs. 
The small-outs provided in Figma will need to be updated, they are currently missing titles.

**Comment by ambroseyau** [comment]
**Changing the name from Smallout to Small-Callout for easier understanding, especially for new onboard designers. Will discuss with Devs what we will be calling this in code (eg. small-callout or callout-small)** 

**The Small-Callout Figma UI we received was inconsistent with our current normal size Call-out.**
- different background color
- top and bottom padding are different
- missing title (saw a Small-Callout with a title in an app demo)

Had a discussion with the Devs to identify spacing and line-height design tokens and how we can use this to create the Small-Callout.

**Design token's discussion with Devs:**
- currently not using the "Spacing" design token
- currently using "Line-height" and "Font-Size" Design token
- Need to determine if "font-size" designs to need to be introduced because we want users to use standard tags. Examples: <p> <h1>

**Currently working on**
- Updating the "Spacing" design token
- Reviewing the "line-height" and "font-size" design tokens
- Create Small-Callout on Figma

**Future work**
- Ensure Small-Callout is part of the regular Callout component and allow users to switch between different sizes easily
- Documentation
