### ISSUE TITLE
Design documentation update - investigate "text field" name discrepancy

### ISSUE THREAD

**Issue by Spark450** [GovAlta/ui-components#459]
Current the ui component name is "input" which is the native HTML element name, would like to align to this naming convention.

**As a:** Design system team
**I want:** To have designers and developers to be using a common language when referencing a component
**so that:** Communication within teams can be more clear.

### Acceptance criteria
- [ ] Update Figma component name to "input"
- [ ] Update references of component name in documentation to "input"
- [ ] Update documentation format to "new" style.

### Presentable outcomes
- [ ] I can show updated documentation and Figma component during the sprint review

### Sprint Ready Checklist 

- Acceptance criteria defined 
- Team has defined steps to satisfy acceptance criteria 
- Acceptance criteria is verifiable / testable 
- External / 3rd Party dependencies identified

### Related issues:
GitHub issue: corresponding Dev issue #436 

### Resources:
**Mockups:** [Text field](https://www.figma.com/file/3pb2IK8s2QUqWieH79KdN7/Components---DIO-DS?node-id=458%3A16019)
**Testing URL:** *[If applicable a URL to the testing branch]*

**Comment by ambroseyau** [comment]
Had a chat with Rajan on March 11 in regards to the input type label.
Setting up a meeting with Chris so we can get an aligned direction if we want to update the Figma component name to "input" instead of "text field"

**Comment by ambroseyau** [comment]
Had a discussion with @bluekurinji @chrisolsen and we came to the conclusion that we decided not to move forward with updating the Figma component name.

There are 2 different audiences so it would not be valuable to update the Figma file to from "text field" to "input". Also, some developers consider "text-field" as "input" while others mental model is the opposite. However, the most important note is that all the developers understand the relationship between "text-field" and "input" so they will have no problem understanding what we have currently.

Moving forward, we will revisit this in the next quarter or two. We will talk to the developers to see if they are confused with the component name in Figma or having trouble collaborating with FEDs due to this component name (text field). We will then determine if there's a need to update this and figure out if we need to rename the Figma component names or the component names in the code.
